#!/usr/bin/env node

const buildTool = require('./buildTool');
const remoteBuild = require('./remoteBuild');
const args = require('process').argv;

if (args.length > 2) {
    const buildPath = args[2];
    remoteBuild.buildApp(buildPath);
} else {
    buildTool.build();
}