//Files and folders from appRoot to be copied to buid-src
const filesAndDirectoriesToBuild = [
  "jimu.js",
  "themes",
  "libs",
  "dynamic-modules",
  "config.json",
  "widgets"
];

//Built files in buildOutput/app-packages
//to be copied to buildOutput/app
const builtFilesToCopyToAppOutput = [
  ["jimu", "jimu.js"], //[ originName, destName ]
  "themes",
  "widgets",
  "libs",
  "dynamic-modules",
  "predefined-apps/default/config.json", //missing in some api versions, thus tryCopy.
  "config.json",
  "build-report.txt" //generated by dojo build process
];

//Built files and folders in buildOutput/app-packages
//to be copied to buildOutput/app/arcgis-js-api
const builtFilesToCopyToArcgisJsFolder = [
  "dgrid/css",
  "dijit/icons",
  "dijit/themes/claro/claro.css",
  "dijit/themes/claro",
  "dojo/resources",
  "dojo/dojo.js",
  "dojo/nls",
  "dojox/gfx/svg.js",
  "dojox/grid/resources",
  "dojox/layout/resources",
  "dojox/layout/resources/ResizeHandle.css",
  "esri/css",
  "esri/dijit",
  "esri/images",
  "esri/main.js",
  "esri/layers/VectorTileLayerImpl.js",
  "esri/layers/vectorTiles",
  "esri/layers/nls", // wont work in api version 3.20
  "dojox/widget/ColorPicker" //needed by draw widget
];

//Unbuilt files and folders in appRoot
//to be copied to buildOutput/app
const unbuiltFiles = [
  "index.html",
  "init.js",
  "simpleLoader.js",
  "web.config",
  "images",
  "config-readme.txt",
  "readme.html",
  "configs",
  "package.json"
];

exports.builtFilesToCopyToAppOutput = builtFilesToCopyToAppOutput;
exports.filesAndDirectoriesToBuild = filesAndDirectoriesToBuild;
exports.builtFilesToCopyToArcgisJsFolder = builtFilesToCopyToArcgisJsFolder;
exports.unbuiltFiles = unbuiltFiles;
