#!/usr/bin/env node

const buildTool = require('./buildTool');
const remoteBuild = require('./remoteBuild');
const file = require('./file');
const paths = require('./paths');
const program = require('commander');
const path = require('path');

//TODO include samples in usage section for these options.

//TODO improve README.md

//TODO include env.js, init.js and simpleload.js to be built

program.
    version(getVersion())
    .name('esri-wab-build')
    .option('-p, --path <path>', 'Path to web appbuilder app source to be built')
    .option('-a, --with-api-version <number>', 'Create build with custom arcgis js api version. Default is version inside env.js file.')
    .option('-z, --zip-app', 'Zip app final folder after building it')
    .option('-B, --skip-bower-install', 'Prevent (re)installing bower dependencies')
    .option('-L, --with-locales <locales>', 'Set custom localesList in the generated app.profile.js before dojo build.')
    .parse(process.argv);

validateOptions(program);
run(program);


function validateOptions(program){
    if (program.withApiVersion && isNaN(program.withApiVersion)) {
        console.error('error: option -a or --with-api-version requires a version number.');
        process.exit(1);
    }
}

function run(options){
    if (options.path) {
        remoteBuild.buildApp(options);
    } else {
        buildTool.build(options);
    }
}

function getVersion() {
    let packageJson = file.readJson(path.join(__dirname, '../package.json'));
    return packageJson.version;
}