#!/usr/bin/env node

const buildTool = require('./buildTool');
const remoteBuild = require('./remoteBuild');
const file = require('./file');
const paths = require('./paths');
const program = require('commander');
const path = require('path');

program.
    version(getVersion())
    .option('-z, --zip-app', 'Build process will zip app after building it')
    .option('-p, --path <path>', 'Path to web appbuilder app source to be built')
    .option('-B, --skip-bower-install', 'Prevent from reinstalling bower dependencies')
    .parse(process.argv);

if (program.path) {
    remoteBuild.buildApp(program);
} else {
    buildTool.build(program);
}

if(program.zipApp){
    file.createZipFromTo(paths.appOutput, paths.outputZip);
}

function getVersion(){
    let packageJson = file.readJson(path.join(__dirname, '../package.json'));
    return packageJson.version;
}